sudo: required
services:
  - docker

before_install:
  - docker build -t amitdocker/aws -f ./client/Dockerfile.dev ./client

script:
  - docker run amitdocker/aws npm test -- --coverage

after_success:
  - docker build -t fullstackamit/multi-client ./client
  - docker build -t fullstackamit/multi-nginx ./nginx
  - docker build -t fullstackamit/multi-server ./server
  - docker build -t fullstackamit/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fullstackamit/multi-client
  - docker push fullstackamit/multi-nginx
  - docker push fullstackamit/multi-server
  - docker push fullstackamit/multi-worker